language: ruby
cache: bundler
sudo: false
services:
  - mysql

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0

before_script:
  - mysql -e 'create database posty_api_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate
  - bundle exec rake api_key:generate

script:
  - bundle exec rake spec
  - bundle exec rubocop